spring:
  profiles:
    active:
    - mariadb
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
  - classpath*:/mybatis/mapper/**/*.xml

---
spring:
  profiles: h2db
  datasource:
    url: jdbc:h2:file:./target/h2db
    username: sa
  flyway:
    enabled: false

---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/address
    username: root
    password: password
  flyway:
    enabled: false
